// <auto-generated />
using API.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210305143901_AddMoreSeedData")]
    partial class AddMoreSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test Test Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test",
                            Price = 39m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test 2 Test 2 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 2",
                            Price = 339m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Test 3 Test 3 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 3",
                            Price = 499.50m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Test 4 Test 4 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 4",
                            Price = 88m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Test 5 Test 5 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 5",
                            Price = 201.60m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Test 6 Test 6 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 6",
                            Price = 499m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Test 7 Test 7 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 7",
                            Price = 301m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Test 8 Test 8 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 8",
                            Price = 1113m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Test 9 Test 9 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 9",
                            Price = 433.90m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Test 10 Test 10 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 10",
                            Price = 349.22m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Test 11 Test 11 Test",
                            ImgUri = "https://via.placeholder.com/600x400",
                            Name = "Test 11",
                            Price = 3039.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
